title: James Coggan
description: Personal website
baseurl: "/""
url: "https://jamescoggan.com"
twitter_username: mad_team
github_username:  jamescoggan
show_downloads: false
google_analytics: UA-111274362-1
# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
  - jekyll-redirect-from

collections:
  posts:
    output: true
    permalink: /:title/
