title: James Coggan
email: james.coggan@gmail.com
description: >
  Android craftsmanship passionate for IoT
baseurl: ""
url:  https://jamescoggan.com
logo: "/assets/img/logo.png"

paginate: 10
paginate_path: "/blog/page:num/"
markdown: kramdown
sass:
    sass_dir: assets/css/sass
    style: compressed

plugins:
  - jekyll-gist
  - jekyll-paginate
